### ISSUE TITLE
There is a Beep Sound after install this?

### ISSUE THREAD

**Issue by SharkIng** [tarruda/zsh-autosuggestions#79]
Why? is that possible to turn it off??

**Comment by toxster** [comment]
Same here, on OS X 10.10.5, todays zsh version, first keystrokes triggers bell..

**Comment by mikesmayer** [comment]
Due to using a forked version of zsh-syntax-highlighting, you also get along the bug that causes a [bell on every keystroke][1], using zsh-users/zsh-syntax-highlighting instead I avoided this bug.

You have to change the syntax highlighting pluging: git clone git://github.com/zsh-users/zsh-syntax-highlighting ~/.zsh/zsh-syntax-highlighting

**Comment by tkkcc** [comment]
this [zsh option](https://linux.die.net/man/1/zshoptions) helps
```sh
setopt No_Beep
```
